### ISSUE TITLE
Error "Cannot read property 'remappings' of null"

### ISSUE THREAD

**Issue by dwlee** [robotics-in-concert/rocon_authoring#12]
다음과 같은 에러가 발생합니다. 
```
resource allocation timeout.
/home/dwlee/work/authoring_ws/src/rocon_authoring/node_modules/fibers/future.js:245
						throw(ex);
						      ^
TypeError: Cannot read property 'remappings' of null
    at Engine.runScheduledAction (/home/dwlee/work/authoring_ws/src/rocon_authoring/engine.js:323:8)
    at eval (eval at <anonymous> (/home/dwlee/work/authoring_ws/src/rocon_authoring/engine.js:197:10), <anonymous>:108:29)

```

**Comment by eskim** [comment]
close 하겠습니다. 다시 발생하면 알려주세요.
